### ISSUE TITLE
Assume role failing via WebIdentity

### ISSUE THREAD

**Issue by SheverNts** [oxyno-zeta/s3-proxy#390]
**Describe the bug**
Error when trying to access STS endpoint (sts.us-east-1.amazonaws.com), It is using http endpoint instead of https.

Error:
Internal Server Error
WebIdentityErr: failed to retrieve credentials caused by: RequestError: send request failed caused by: Post "http://sts.us-east-1.amazonaws.com/": read tcp 100.64.15.129:48714->67.220.245.46:80: read: connection reset by peer

**Screenshots**
<img width="1590" alt="Screenshot 2023-10-17 at 6 46 56 PM" src="https://github.com/oxyno-zeta/s3-proxy/assets/15715909/d2726dd3-a6e8-49d6-96a6-2bcbfca8301b">

**Version and platform (please complete the following information):**
 - Platform Linux 
 - Arch amd64
 - Version 4.5

**Comment by oxyno-zeta** [comment]
Hello @SheverNts ,

Thanks for your ticket.

The project is using the official V1 SDK and nothing particular has been done to support STS. This is something the client is trying/detecting because you haven't set access key and secret key in the configuration I would say. Or because you put some environment variables.

I don't know how to help you with that. 

Best regards,

Oxyno-zeta

**Comment by SheverNts** [comment]
@oxyno-zeta  Issue resolved after setting disableSSL to false, Seems disableSSL disabling ssl for all aws endpoints 

https://github.com/oxyno-zeta/s3-proxy/blob/82c13bd022583d9d0071535dbf9508de4f0503f9/pkg/s3-proxy/utils/generalutils/utils.go#L200

**Comment by oxyno-zeta** [comment]
Interesting to know, thanks. Is your problem fixed ?

**Comment by SheverNts** [comment]
@oxyno-zeta  Problem fixed after enabling the ssl via disableSSL.
Thanks
